### ISSUE TITLE
Weird fingerprinting of images

### ISSUE THREAD

**Issue by mydea** [ember-engines/ember-asset-loader#43]
I'm not 100% sure if this belongs here, but I think so.

I'm using lazyLoading engines.
In one of the engines, I have the following image:

```html
<img src="assets/images/test.png">
```

When building, I use fingerprinting and a CDN with the following configuration:

```js
// host-app's ember-cli-build.js
// ...

var cdnPrepend = false;
if (env === 'staging') {
  cdnPrepend = 'https://XXX.cloudfront.net/';
}
if (env === 'production') {
  cdnPrepend = 'https://YYY.cloudfront.net/';
}

var app = new EmberApp(defaults, {
 fingerprint: {
      enabled: isProductionLikeBuild,
      prepend: cdnPrepend,
      extensions: ['js', 'css', 'png', 'jpg', 'gif', 'map', 'svg']
    },
   assetLoader: {
      generateURI: function(filePath) {
        if (cdnPrepend) {
          // Prevent duplicate slashes
          return cdnPrepend.substr(0, cdnPrepend.length - 1) + filePath;
        }
        return filePath;
      }
    }
});
```

I get the image

```html
<img src="https://XXX.cloudfront.net/assets/engines-dist/my-engine-name/assets/images/test-FINGERPRINT.png">
```

So basically, it is weirdly duplication the `assets` portion to before the `engines-dist`, which makes this fail. I'm not quite sure where/how this comes from.

Also, not sure if this is related, but the url is also wrongly rewritten if I use `/assets/xxx`. Leaving the leading slash doesn't work in development for me, but in production it lead to `/https://XXX.cloudfront.net/assets/engines-dist/my-engine-name/assets/images/test-FINGERPRINT.png`, which of course also doesn't work.

If I set `lazyLoading: false`, it works as expected.

I'm using:
ember-engines@0.4.0
ember@2.10.2
ember-cli@2.10.0

**Comment by nathanhammond** [comment]
This is an issue, likely not related to ember-asset-loader: https://github.com/ember-cli/ember-cli/issues/6265 I'm closing this as it's being tracked upstream. `broccoli-asset-rev` needs some TLC (and an owner).

I'm appreciative of the additional information that you've provided here.
