### ISSUE TITLE
How use contentFor in engines

### ISSUE THREAD

**Issue by brunowego** [ember-engines/ember-asset-loader#47]
So, I have a engine with `lazyLoading: false` inside a fresh ember app. My engine have addons and one of them have the code below:

```js
# index.js
/* eslint-env node */
'use strict';

module.exports = {
  name: 'ember-cli-neutral',

  contentFor(type, config) {
    if (type === 'head') {
      if (config.googleFonts) {
        let families = config.googleFonts.join('|');

        return '<link href="https://fonts.googleapis.com/css?family=' + families + '" rel="stylesheet">'; // eslint-disable-line
      }
    }
  }
};
```

```js
# environment.js
/* eslint-env node */
'use strict';

module.exports = () => {
  const ENV = {
    googleFonts: [
      'Roboto:400,500'
    ]
  };

  return ENV;
};
```

If I run engine separately the link of google fonts works perfectly, but if I run inside the fresh ember app not.

Perhaps a feature for future or it's outside the scope of this project?

**Comment by trentmwillis** [comment]
This doesn't seem to have anything to do with the ember-asset-loader. Perhaps you meant to open this issue on the [ember-engines addon repo](https://github.com/ember-engines/ember-engines)?

**Comment by brunowego** [comment]
Sorry for the mistake. I thought it would be related. 👍
