### ISSUE TITLE
Should not include empty files in generated asset manifest.

### ISSUE THREAD

**Issue by rwjblue** [ember-engines/ember-asset-loader#50]
When working on a self contained engine it is quite possible to end up without any vendor'ed JS or CSS. In that scenario `engine-vendor.css` and `engine-vendor.js` are empty files. 

I propose that empty files should be excluded from the generated `asset-manifest.json` by default.

Any objections?

**Comment by mike183** [comment]
I'd like to second this. In our use case, a vast majority of the engines are producing empty files that are being downloaded.

**Comment by trentmwillis** [comment]
Makes sense to me!

**Comment by rwjblue** [comment]
@dgeb / @nathanhammond - Y'all have any objections to this?
