### ISSUE TITLE
Improve CI to avoid dependency drift

### ISSUE THREAD

**Issue by lennyburdette** [ember-engines/ember-asset-loader#65]
Writing down tasks from our discussion at the contributors workshop:

- [x] Switch to yarn so we can use a lockfile.
- [x] Remove PhantomJS from .travis.yml (jQuery dropped support for Phantom 1.x and Ember dropped support for Phantom entirely.)
- [x] Use Travis stages to run tests with both `yarn install` and `yarn install  --no-lockfile`.

cc @rwjblue @spencer516

**Comment by rwjblue** [comment]
👍

**Comment by lennyburdette** [comment]
Completed by #68
