### ISSUE TITLE
On Windows, engine asset paths use back slashes instead of forward slashes

### ISSUE THREAD

**Issue by williamhector** [ember-engines/ember-asset-loader#67]
I didn't notice this issue until after production.
It seems to be handled well by most browsers, but we have some users still on FF 48, which seems to sometimes crash when page loading inside a routable engine. However, this is ultimately irrelevant.

Our production app is https://www.typingtournament.com/
If you inspect the dom, you'll see the engine assets in `<head>` use back slashes instead of forward slashes.
I develop on Windows, so I assume that is the issue because I haven't seen anyone else report this before.

I added a console.log like this in my ember-cli-build.js file:
```
let app = new EmberApp(defaults, {
	...
	assetLoader: {
		generateURI: function(filePath){
			console.log(filePath);
			return filePath;
		}
	},
	...
});
```

and my build log showed this:
```
d:\src\edalive\typingtournament\client\src>ember build
\ Building\engines-dist\tt-app\assets\engine-vendor.js
\engines-dist\tt-app\assets\engine.js
\engines-dist\tt-teacher\assets\engine-vendor.css
\engines-dist\tt-teacher\assets\engine-vendor.js
\engines-dist\tt-teacher\assets\engine.css
\engines-dist\tt-teacher\assets\engine.js
\engines-dist\tt-web\assets\engine-vendor.css
\engines-dist\tt-web\assets\engine-vendor.js
\engines-dist\tt-web\assets\engine.css
\engines-dist\tt-web\assets\engine.js
cleaning up...
Built project successfully. Stored in "dist/".
```

I'll fix this with js string manipulation in the generateURI method for now, but this should probably also be handled better.

**Comment by williamhector** [comment]
Forgot to mention I'm using 0.3.1 (engines 0.5.14)

**Comment by williamhector** [comment]
Screenshot of production <head> for after we release our fix:
![engines](https://user-images.githubusercontent.com/3031386/37501146-189b94e2-2921-11e8-8fa1-db2fbfeff680.PNG)

**Comment by mike183** [comment]
There is already a PR here, https://github.com/ember-engines/ember-asset-loader/pull/62

**Comment by williamhector** [comment]
Sorry, I only checked issues.

**Comment by mike183** [comment]
@williamhector It could actually be a good idea to keep the issue open as the PR is yet to be merged.

I was just pointing out that there was already an open PR to resolve the issue 🙂

**Comment by mike183** [comment]
@rwjblue I think we can close this now as the PR has been merged 🙂

**Comment by rwjblue** [comment]
Thank you!
