### ISSUE TITLE
CSS asset loader, `onload` event called too soon. (can only repro on firefox)

### ISSUE THREAD

**Issue by Duder-onomy** [ember-engines/ember-asset-loader#70]
I am running into an issue on firefox + lazy ember-engines.  

Browsers fire the `onload` event for link elements after the file is downloaded and parsed but BEFORE the css is applied to the document. [mdn docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link)

![image](https://user-images.githubusercontent.com/1612785/41928884-8230fdca-792b-11e8-84b2-51a45461b043.png)

I believe the [css loader](https://github.com/ember-engines/ember-asset-loader/blob/master/addon/loaders/utilities.js#L17) should be updated with a RAF or something similar to ensure the browser has painted BEFORE allowing the engine to render. 

On chrome, this is no big deal, on firefox, I can actually see the content from my async engine render (incorrectly) before css is applied and everything snaps into place. 

My unacceptable workaround: 

```javascript
// beforeModel hook of the async engines application route
beforeModel() {
  if (browserIsFirefox) {
      return new RSVP.Promise((resolve) => {
          document.body.getBoundingClientRect(); // force a reflow
          getRequestAnimationFrame(resolve); // ensure there is at least 1 paint before moving forward
      });
  }
  return true;
}
```

I am about to launch a new feature on TheDyrt where you can repro this 100% of the time.

**Comment by villander** [comment]
@Duder-onomy can you reproduce this with a public repo, please?

**Comment by Duder-onomy** [comment]
I can... but its a lot of work. 
I think I will have some time this weekend to try and spin it up.
It on happens in fastboot + async engines. 

If you look at this page on theDyrt: https://thedyrt.com/list/top-campgrounds-in-each-of-america-s-59-national-parks

You will briefly see a spinner for the whole page (only on hard refresh). But yeah, I understand what you'r looking for.

**Comment by villander** [comment]
@rwjblue can you close this, by **for inactivity and lack of reproduction** please?
