### ISSUE TITLE
option to make resetting asset state in tests less noisy

### ISSUE THREAD

**Issue by fivetanley** [ember-engines/ember-asset-loader#74]
It would be great if there was a way to make this less noisy: https://github.com/ember-engines/ember-asset-loader/blob/ad0d51898480b426c35853cdf441828c865cd375/addon-test-support/loaded-asset-state.js#L114

If it runs in `afterEach` after every test, that can really pollute a test run's output.

**Comment by rwjblue** [comment]
@fivetanley - Lets make that only print out once.  I'm thinking a simple boolean in module scope, what do you think?

**Comment by fivetanley** [comment]
@rwjblue that sounds good to me, i'll make a PR

**Comment by villander** [comment]
@rwjblue we can close this issue...
